set_property LOC E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
create_clock -add -name sys_clk_pin -period 10.00 [get_ports clk]

set_property LOC H17 [get_ports LED[0]]
set_property LOC K15 [get_ports LED[1]]
set_property LOC J13 [get_ports LED[2]]
set_property LOC N14 [get_ports LED[3]]
set_property LOC R18 [get_ports LED[4]]
set_property LOC V17 [get_ports LED[5]]
set_property LOC U17 [get_ports LED[6]]
set_property LOC U16 [get_ports LED[7]]
set_property LOC V16 [get_ports LED[8]]
set_property LOC T15 [get_ports LED[9]]
set_property LOC U14 [get_ports LED[10]]
set_property LOC T16 [get_ports LED[11]]
set_property LOC V15 [get_ports LED[12]]
set_property LOC V14 [get_ports LED[13]]
set_property LOC V12 [get_ports LED[14]]
set_property LOC V11 [get_ports LED[15]]
set_property LOC C12 [get_ports CPU_RESETN]
set_property LOC C17 [get_ports JA[0]]
set_property LOC D18 [get_ports JA[1]]
set_property LOC E18 [get_ports JA[2]]
set_property LOC G17 [get_ports JA[3]]
set_property LOC D17 [get_ports JA[4]]
set_property LOC E17 [get_ports JA[5]]
set_property LOC F18 [get_ports JA[6]]
set_property LOC G18 [get_ports JA[7]]
set_property LOC A3 [get_ports VGA_R[0]]
set_property LOC B4 [get_ports VGA_R[1]]
set_property LOC C5 [get_ports VGA_R[2]]
set_property LOC A4 [get_ports VGA_R[3]]
set_property LOC C6 [get_ports VGA_G[0]]
set_property LOC A5 [get_ports VGA_G[1]]
set_property LOC B6 [get_ports VGA_G[2]]
set_property LOC A6 [get_ports VGA_G[3]]
set_property LOC B7 [get_ports VGA_B[0]]
set_property LOC C7 [get_ports VGA_B[1]]
set_property LOC D7 [get_ports VGA_B[2]]
set_property LOC D8 [get_ports VGA_B[3]]
set_property LOC B11 [get_ports VGA_HS]
set_property LOC B12 [get_ports VGA_VS]
set_property LOC C4 [get_ports rx]
set_property LOC D4 [get_ports tx]

set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {CPU_RESETN}]
set_property IOSTANDARD LVCMOS33 [get_ports {JA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {JA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {JA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {JA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {JA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {JA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {JA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {JA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_HS}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_VS}]
set_property IOSTANDARD LVCMOS33 [get_ports {rx}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx}]










